### PR TITLE
updating dependencies via bower

### PR DESCRIPTION
**Pull request by madole**
bower install from root will inject the dependencies into
client/src/libs
- index.html has been updated to include these (to be replaced with
  requireJS)
- templates have been updated to use Bootstrap3
- handlebars templates has been updated to use the new link-to and
  bind-attr syntax
- emberJS code updated to use the new ember syntax

### CODE REVIEW

**Comment by madole** [comment]
Just spotted the gulp bower-install injects dependencies into the index.html so no need for requireJS yet. 
Will need it to inject emberjs files though

**Comment by martinmicunda** [comment]
I have actually lot of changes too but I need to merge them with yours so it would be good when there won't be any changes till 2mor .. so I can push my code

**Comment by madole** [comment]
ok, I'll not make any more changes today, will keep an eye out for your pull request

**Comment by chrislaughlin** [comment]
We should probably use trello to mark what tasks we are working on

**Comment by martinmicunda** [comment]
We could have a meeting on saturday morning to discuss that?

**Comment by madole** [comment]
I'm off to a beach house this weekend so no wifi. Can we chat on HipChat about it?

**Comment by chrislaughlin** [comment]
I should be free for a meeting, we could probably draw up a task list for
getting the current ember code to what we need then the remaining login
tasks.

On Wednesday, May 21, 2014, Martin Micunda notifications@github.com wrote:

> We could have a meeting on saturday morning to discuss that?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cam-technologies/time-booker/pull/8#issuecomment-43729242
> .

## 

Regards

Chris Laughlin

**Comment by martinmicunda** [comment]
so I can have a quick chat with you Chris on sat?

**Comment by chrislaughlin** [comment]
Sure we can use hip chat I wouldn't mind a sleep in on Saturday, just
posting now. It think as long as we keep all talks on the cards in trellis
then when working on that issue create it on GitHub then assign the issue
to yourself. When working make sure that you are now looking at the same
task as someone else, this should keep everyone updated

On Wednesday, May 21, 2014, Martin Micunda notifications@github.com wrote:

> so I can have a quick chat with you Chris on sat?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cam-technologies/time-booker/pull/8#issuecomment-43731000
> .

## 

Regards

Chris Laughlin

**Pull request merged**
