### PR TITLE
PR: moving migrations and adding gulp migration command fixes #34

### LINKED ISSUE #34: User Server Side Changes
Connect Node server application to mongo instance 
- Add the express config for the mongo connections (linked to task #33 )

Routes
- Update login route to check DB for user details
- Add Logout route

### PR DESCRIPTION
**Pull request by chrislaughlin**
To clear up migrations, these for now will be used for seeding data into the development data base, we can also use it for applying changes to existing data in production e.g. if we need to add or remove attributes on a schema. Currently they only run on development *_pending production config *_\* when we start to use them for production we can flag changes that are dev only by checking the env. Any questions? we can chat on here or on hipchat. Think of them as the same as what we had on RSQE with the 'gradle applyDBupdates'

### CODE REVIEW

**Comment by madole** [comment]
Build failing on JS Hint, I suspect if you just fix them up, it'll pass. Are you using webstorm? It hint's as you go. If you're using SublimeText2, switch to SublimeText3 and us JSGutter with JSHint and it'll hint your code as you type it. Runs on node, pretty cool!

**Comment by chrislaughlin** [comment]
I forgot to add my fixes lol will add them now

**Comment by chrislaughlin** [comment]
I made the link changes then rand commit without adding the changes to the commit to the lint passed but when committing the changes did not push up, #gitfaill

**Comment by chrislaughlin** [comment]
It passed!!!! is everyone clear on the reason for having migrations?

**Comment by martinmicunda** [comment]
Yeap

**Comment by chrislaughlin** [comment]
merge the request MARTIN!!!!!!!

**Pull request merged**
