### PR TITLE
PR: fixing #30

### PR DESCRIPTION
**Pull request by chrislaughlin**
If user is not logged in, re-direct to login route else show index. 
Updating readme for e2e test

### CODE REVIEW

**Comment by madole** [comment]
Your tab spacing is set to 4. I'm pretty sure we agreed somewhere that it should be set to two. Also, you have your name injected into the comments, I think this is unnecessary as we're doing pull requests. So we can see clearly who wrote the code and if you really want to see who wrote the code, use "git blame"

**Comment by chrislaughlin** [comment]
I'll change my IDE settings

On Monday, June 9, 2014, madole notifications@github.com wrote:

> Your tab spacing is set to 4. I'm pretty sure we agreed somewhere that it
> should be set to two. Also, you have your name injected into the comments,
> I think this is unnecessary as we're doing pull requests. So we can see
> clearly who wrote the code and if you really want to see who wrote the
> code, use "git blame"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cam-technologies/time-booker/pull/31#issuecomment-45484111
> .

## 

Regards

Chris Laughlin

**Comment by martinmicunda** [comment]
Spacing should be set in [.editorconfig](https://github.com/cam-technologies/time-booker/blob/master/.editorconfig) file.

**Comment by chrislaughlin** [comment]
does this apply for web storm

**Comment by madole** [comment]
I didn't know we even had that file, http://editorconfig.org/#download says there's plugins to download. Can we put this in the read me?

**Comment by chrislaughlin** [comment]
installed Ill check the auto format for web storm to see if it picks up the settings, also I prefer 4 spaces for a tab, looks cleaner

**Comment by martinmicunda** [comment]
yeah me too

**Comment by madole** [comment]
Me too, but I thought I read somewhere we decided on two... I'm good with 4... We use 2 in work and it shits me

**Pull request merged**
